version: '3.4'

services:
  crudapp:
    image: crudapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=18.233.166.222:9229", "server.js"]
